### ISSUE TITLE
Use the built in retry functionality in the requests module, rather than using custom decorators 

### ISSUE THREAD

**Issue by Serhiy1** [datatrails/datatrails-python#95]
**Is your feature request related to a problem? Please describe.**
Currently, we use a custom decorator function to retry 429 failures.  

**Describe the solution you'd like**
we should use the built in retry mechanism in the requests library. 
https://findwork.dev/blog/advanced-usage-python-requests-timeouts-retries-hooks/

**Comment by eccles** [comment]
current backoff logic is good enough - no advantage perceoved using the requests feature
